<?php

namespace TacticalExcel\Component;

use PhpOffice\PhpSpreadsheet\Spreadsheet as PhpSpreadsheet;

class Spreadsheet extends PhpSpreadsheet
{
    public function __construct()
    {
        parent::__construct();
        $this->removeSheetByIndex(0);
    }

    public function addSheetWithTitle($title)
    {
        $sheet = new Worksheet($this, $title);
        $this->addSheet($sheet);
        return $this;
    }

    /**
     * @param int $pIndex
     * @return Worksheet
     * @throws \PhpOffice\PhpSpreadsheet\Exception
     */
    public function getSheet($pIndex)
    {
       return parent::getSheet($pIndex); // TODO: Change the autogenerated stub
    }

    /**
     * @return Worksheet
     * @throws \PhpOffice\PhpSpreadsheet\Exception
     */
    public function getActiveSheet()
    {
        return parent::getActiveSheet(); // TODO: Change the autogenerated stub
    }
}